version: "3.7"
services:
  spark-master:
    image: tan4ek.nas.local:5000/spark-master:2.3.1
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080" 
      - "7077:7077"
    volumes:
      - /mnt/NAS-tan4ek/Public/spark-data:/mnt/NAS-tan4ek/Public/spark-data
    environment:
      - "SPARK_LOCAL_IP=spark-master"
      - "SPARK_MASTER_WEBUI_PORT=8080"
      - "SPARK_DRIVER_MEMORY=513m"
      - "SPARK_WORKER_CORES=2"
      - "SPARK_PUBLIC_DNS=${EXTERNAL_IP}"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - spark_net
  spark-worker:
    image: tan4ek.nas.local:5000/spark-worker:2.3.1
    container_name: spark-worker
    hostname: spark-worker
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    env_file: ./env/spark-worker.sh
    environment:
      - "SPARK_LOCAL_IP=spark-worker"
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_WEBUI_PORT=8081"
      - "SPARK_WORKER_MEMORY=512m"
      - "SPARK_WORKER_CORES=2"
      - "SPARK_PUBLIC_DNS=${EXTERNAL_IP}"
    volumes:
      - /mnt/NAS-tan4ek/Public/spark-data:/mnt/NAS-tan4ek/Public/spark-data
    deploy:
      placement:
        constraints: [node.role != manager]
    networks:
      - spark_net
networks:
  spark_net:
    driver: overlay
    attachable: true
